/******************************CREATE DATABASE********************************/

CREATE DATABASE QUANLYSINHVIEN_B3_3_2574802010111
GO 
USE QUANLYSINHVIEN_B3_3_2574802010111

/************************TAO BANG KHOA QUAN LY SINH VIEN*************************/
CREATE TABLE KHOA(MAKHOA VARCHAR(4) NOT NULL ,
			TENKHOA NVARCHAR(30) NOT NULL,
			      NAMTHANHLAP INT NOT NULL) 

/************************TAO BANG SVIEN QUAN LY SINH VIEN*************************/
CREATE TABLE SVIEN(TEN NVARCHAR(30) NOT NULL,
			MASV INT NOT NULL,
			   NAM INT NOT NULL,
				 NGAYSINH DATE NULL,
			      MAKH VARCHAR(4) NOT NULL)

/************************TAO BANG MHOC QUAN LY SINH VIEN*************************/
CREATE TABLE MHOC(TENMH NVARCHAR(30) NOT NULL,
			MAMH VARCHAR(8) NOT NULL,
			   TINCHI INT NOT NULL,
			      MAKH VARCHAR(4) NOT NULL)

/************************TAO BANG DKIEN QUAN LY SINH VIEN*************************/
CREATE TABLE DKIEN(MAMH VARCHAR(8) NOT NULL,
			MAMH_TRUOC VARCHAR(8) NOT NULL
			)


/************************TAO BANG HPHAN QUAN LY SINH VIEN*************************/
CREATE TABLE HPHAN(MAHP INT NOT NULL,
			MAMH VARCHAR(8) NOT NULL,
			   HOCKY VARCHAR(5) NOT NULL,
			      NAM INT NOT NULL,
					GV NVARCHAR(30) NULL, 
						NGAYBD DATE, 
							NGAYKT DATE
			)

/************************TAO BANG KQUA QUAN LY SINH VIEN*************************/
CREATE TABLE KQUA(MASV INT NOT NULL,
			   MAHP INT NOT NULL,
			      DIEM FLOAT NOT NULL
			)

/*****************************************************************************/
ALTER TABLE KHOA
ADD CONSTRAINT PK_KHOA
PRIMARY KEY (MAKHOA)

ALTER TABLE SVIEN 
ADD CONSTRAINT PK_SVIEN
	PRIMARY KEY (MASV)

ALTER TABLE SVIEN
ADD CONSTRAINT FK_SVIEN_MAKH
	FOREIGN KEY (MAKH)
	REFERENCES KHOA (MAKHOA)

ALTER TABLE MHOC
ADD CONSTRAINT PK_MHOC
PRIMARY KEY (MAMH)

ALTER TABLE MHOC
ADD CONSTRAINT FK_MHOC_MAKH
FOREIGN KEY (MAKH)
REFERENCES KHOA(MAKHOA)

ALTER TABLE DKIEN
ADD CONSTRAINT PK_DKIEN
PRIMARY KEY (MAMH, MAMH_TRUOC)

ALTER TABLE DKIEN
ADD CONSTRAINT FK_DKIEN_MAMH
FOREIGN KEY (MAMH)
REFERENCES MHOC(MAMH)

ALTER TABLE DKIEN
ADD CONSTRAINT FK_DKIEN_MAMH_TRUOC
FOREIGN KEY (MAMH_TRUOC)
REFERENCES MHOC(MAMH)

ALTER TABLE HPHAN
ADD CONSTRAINT PK_HPHAN
PRIMARY KEY (MAHP)

ALTER TABLE HPHAN
ADD CONSTRAINT FK_HPHAN_MAMH
FOREIGN KEY (MAMH)
REFERENCES MHOC(MAMH)

ALTER TABLE KQUA
ADD CONSTRAINT PK_KQUA
	PRIMARY KEY (MASV, MAHP)

ALTER TABLE KQUA 
ADD CONSTRAINT FK_KQUA_MASV
	FOREIGN KEY (MASV)
	REFERENCES SVIEN (MASV)

ALTER TABLE KQUA 
ADD CONSTRAINT FK_KQUA_MAHP
	FOREIGN KEY (MAHP)
	REFERENCES HPHAN (MAHP)

/***********************************ALTER***********************************/
--1. Thêm một ràng buộc thiết lập giá trị mặc định là 1995 cho cột NAMTHANHLAP (Năm thành lập) của bảng KHOA.
ALTER TABLE KHOA ADD CONSTRAINT DF_KHOA_NAMTHANHLAP DEFAULT 1995 FOR NAMTHANHLAP

--2. Thêm ràng buộc kiểm tra cột DIEM (Điểm) trong bảng KQUA (Kết quả) là một số lớn hơn bằng 0.
ALTER TABLE KQUA ADD CONSTRAINT CK_KQUA_DIEM CHECK (DIEM >= 0)

--3. Thêm ràng buộc kiểm tra cột MAKHOA (Mã khoa) trong bảng KHOA (Khoa) phải bắt đầu bằng 2 ký tự ‘KH’.
ALTER TABLE KHOA ADD CONSTRAINT CK_KHOA_MAKHOA CHECK (MAKHOA LIKE 'KH%')

--4. Thêm ràng buộc kiểm tra cột HOCKY (Học kỳ) trong bảng HPHAN (Học phần) phải là từ 1 đến 9.
ALTER TABLE HPHAN ADD CONSTRAINT CK_HPHAN_HOCKY CHECK (HOCKY IN ('1', '2', '3', '4', '5', '6', '7', '8', '9'))

--5. Thêm ràng buộc kiểm tra cột TINCHI (Tín chỉ) trong bảng MHOC (Môn học) phải là một trong những số (1, 2, 3, 4, 5, 6).
ALTER TABLE MHOC ADD CONSTRAINT CK_MHOC_TINCHI CHECK (TINCHI IN (1, 2, 3, 4, 5, 6))

--6. Thêm ràng buộc kiểm tra cột NGAYKT (Ngày kết thúc) phải cách sau từ 3 tháng trở lên so với NGAYBD (Ngày bắt đầu) của bảng HPHAN (Học phần).
ALTER TABLE HPHAN ADD CONSTRAINT CK_HPHAN_NGAYKT CHECK (NGAYKT >= DATEADD(MONTH, 3, NGAYBD))
