/******************************CREATE DATABASE********************************/

CREATE DATABASE QUANLYVATTU_B3_2574802010111
GO 
USE QUANLYVATTU_B3_2574802010111

/************************TAO BANG VAT TU *************************/
CREATE TABLE VATTU 
( 
	MAVTU VARCHAR(4) NOT NULL, 
	TENVTU NVARCHAR(30) NOT NULL, 
	DVTINH NVARCHAR(10) NOT NULL, 
	DONGIA INT NULL,
	PHANTRAM INT
)  

/************************TAO BANG CTDONDH*************************/
CREATE TABLE CTDONDH ( 
	SODH VARCHAR(4) NOT NULL, 
	MAVTU VARCHAR(4) NOT NULL, 
	NGAYMUA DATE NULL, 
	NGAYGIAO DATE NULL,
	SLDAT INT NULL
)
 
/*************************KHOA CHINH **********************************/
ALTER TABLE VATTU
		ADD CONSTRAINT PK_VATTU 
			PRIMARY KEY (MAVTU)
ALTER TABLE CTDONDH
		ADD CONSTRAINT PK_CTDONDH
			PRIMARY KEY (SODH, MAVTU)

/***************************KHOA NGOAI***************************/
ALTER TABLE CTDONDH 
		ADD CONSTRAINT FK_CTDONDH_MAVTU FOREIGN KEY (MAVTU)
			REFERENCES VATTU(MAVTU)
			
/***************************ALTER******************************/
ALTER TABLE VATTU
ADD CONSTRAINT DF_VATTU_PHANTRAM
DEFAULT 20 FOR PHANTRAM

ALTER TABLE CTDONDH
ADD CONSTRAINT CK_CTDONDH_SLDAT
CHECK (SLDAT BETWEEN 10 AND 50)