/*********************USE DATABASE***************************/
CREATE DATABASE QUANLYSINHVIEN_B5_2574802010111
GO 
USE QUANLYSINHVIEN_B5_2574802010111

/************************TAO BANG SINH VIEN*************************/
CREATE TABLE FACULTY 
(
	ID VARCHAR(5) NOT NULL, 
	FACULTY_NAME NVARCHAR(50) NULL,
	[SESSION] INT NULL, 
	PRIMARY KEY (ID)
)

CREATE TABLE STUDENT
(
	ID VARCHAR(7) NOT NULL ,
	FULLNAME NVARCHAR(50) NOT NULL,
	ADDRESS NVARCHAR(100) NULL, 
	MOBILE VARCHAR(15) NULL,
	YEAR NVARCHAR(10) NULL, 
	MAX_SESSION INT NULL, 
	FACULTY_ID VARCHAR(5) NULL,
	PRIMARY KEY (ID)
)

CREATE TABLE STUDENT_TEMP
(
	ID VARCHAR(7) NOT NULL ,
	FULLNAME NVARCHAR(50) NOT NULL,
	ADDRESS NVARCHAR(100) NULL, 
	MOBILE VARCHAR(15) NULL,
	YEAR NVARCHAR(10) NULL, 
	MAX_SESSION INT NULL, 
	FACULTY_ID VARCHAR(5) NULL
)

----------------------------------
-- Insert //Thêm một hàng dữ liệu vào bảng Sinh viên
INSERT INTO Student
VALUES ('T130377', N'Lý Thị Huyền Châu', N'Nguyễn Khắc Nhu', '0999580654', 1, 10, 'CNTT')
--
INSERT INTO Student (ID, FullName, Address, Mobile, Year, Max_Session, Faculty_ID)
VALUES ('T130388', N'Phạm Minh Huyên', N'Nguyễn Khắc Nhu', '0999580656', 1, 14, 'TOAN')
--
INSERT INTO STUDENT (id, fullname)
VALUES ('T130439', N'Nguyễn Đắc Quỳnh Mi')
--
INSERT INTO FACULTY VALUES
('CNTT', N'Công Nghệ Thông tin', 12),
('TOAN', N'Toán', 12),
('VL', N'Vật Lý', 12)

-- Insert //Thêm nhiều hàng dữ liệu vào bảng Sinh viên
INSERT INTO STUDENT_TEMP SELECT * FROM STUDENT
--
INSERT INTO STUDENT_TEMP (ID, FullName)
SELECT ID, FullName FROM STUDENT

--Update //Thay đổi thông tin của một/nhiều Sinh viên
UPDATE STUDENT
SET ADDRESS = N'PHAN VĂN TRỊ'
--
UPDATE STUDENT
SET ADDRESS = N'VÕ THỊ SÁU'
WHERE ID='T130377' AND YEAR=1
--
UPDATE STUDENT
SET ADDRESS = N'NGUYỄN THÁI SƠN', FULLNAME = N'LÊ AN'
WHERE ID='T130377' AND YEAR=1

-- Update //Sử dụng cấu trúc CASE trong câu lệnh UPDATE
UPDATE STUDENT
SET YEAR= CASE YEAR
WHEN '1' THEN N'Một'
WHEN '2' THEN N'Hai'
WHEN '3' THEN N'Ba'
WHEN '4' THEN N'Tư'
END

-- Delete (có thể không có mệnh đề [from])//Xóa một/nhiều hàng trong 1 bảng Sinh viên
DELETE STUDENT
WHERE ID='T130377'
-- Delete //Xóa toàn bộ dữ liệu trong bảng
TRUNCATE TABLE STUDENT

SELECT * FROM FACULTY
SELECT * FROM STUDENT
SELECT * FROM STUDENT_TEMP