/*TẠ0 BẢNG DATABASE QUANLYMATHANG*/
-- TẠO DATABASE
CREATE DATABASE QUANLYMATHANG
GO
USE QUANLYMATHANG

-- TẠO BẢNG MATHANG
CREATE TABLE MATHANG
(
	MATHANG INT NOT NULL,
	TENHANG VARCHAR(15) NOT NULL,
	SOLUONGTON INT NULL,
	NGAYNHAPHANG DATE
)

-- THÊM CỘT
ALTER TABLE MATHANG
ADD DONVITINH NVARCHAR(10)

-- THAY ĐỔI CỘT
ALTER TABLE MATHANG
ALTER COLUMN TENHANG NVARCHAR(100)

-- XÓA CỘT
ALTER TABLE MATHANG
DROP COLUMN DONVITINH

-- TẠO BẢNG LOAIHANG
CREATE TABLE LOAIHANG(
	MALOAIHANG INT NOT NULL,
	TENLOAIHANG NVARCHAR(15) NOT NULL,
	PRIMARY KEY (MALOAIHANG)
)
-- TẠO KHÓA CHÍNH RIÊNG
ALTER TABLE MATHANG
ADD CONSTRAINT PK_MATHANG
PRIMARY KEY (MATHANG)

-- TẠO TENHANG LÀ DUY NHẤT
ALTER TABLE MATHANG
ADD CONSTRAINT UQ_MATHANG
UNIQUE (TENHANG)

CREATE TABLE MATHANG (
	MATHANG VARCHAR(10) NOT NULL,
	TENHANG NVARCHAR(50) NOT NULL,
	MALOAIHANG INT NULL,
	SOLUONG INT NULL,
	DONVITINH NVARCHAR(20) NULL,
	GIAHANG MONEY NULL,
	PRIMARY KEY (MATHANG),
	UNIQUE (TENHANG)
)

-- TẠO KHÓA NGOẠI BẢNG MATHANG
ALTER TABLE MATHANG
ADD CONSTRAINT FK_MATHANG_MALOAIHANG
FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
