/******************************CREATE DATABASE********************************/
CREATE DATABASE QUANLYVATTU_B4_TH1
GO 
USE QUANLYVATTU_B4_TH1

/************************TAO BANG VAT TU *************************/
CREATE TABLE VATTU 
( 
	MAVTU VARCHAR(4) NOT NULL, 
	TENVTU NVARCHAR(30) NOT NULL, 
	DVTINH NVARCHAR(10) NOT NULL, 
	DONGIA INT NULL,
	PHANTRAM INT
) 

/************************TAO BANG CTDONDH*************************/
CREATE TABLE CTDONDH ( 
	SODH VARCHAR(4) NOT NULL, 
	MAVTU VARCHAR(4) NOT NULL, 
	NGAYMUA DATE NULL, 
	NGAYGIAO DATE NULL,
	SLDAT INT NULL
)
/************************TAO BANG NHACUNGCAP*************************/
CREATE TABLE NHACUNGCAP ( 
	MANCC VARCHAR(4) NOT NULL, 
	TENNCC NVARCHAR(30) NOT NULL 
)
/*************************KHOA CHINH **********************************/
ALTER TABLE VATTU
		ADD CONSTRAINT PK_VATTU 
			PRIMARY KEY (MAVTU)
ALTER TABLE CTDONDH
		ADD CONSTRAINT PK_CTDONDH
			PRIMARY KEY (SODH, MAVTU)

/***************************KHOA NGOAI***************************/
ALTER TABLE CTDONDH 
		ADD CONSTRAINT FK_CTDONDH_MAVTU FOREIGN KEY (MAVTU)
			REFERENCES VATTU(MAVTU)
			
/***************************ALTER******************************/
----TẠO RÀNG BUỘC GIÁ TRỊ MẶC ĐỊNH CHO CỘT NGÀY MUA
ALTER TABLE CTDONDH
ADD CONSTRAINT DF_CTDONDH_NGAYMUA
	DEFAULT GETDATE() FOR NGAYMUA
---TẠO RÀNG KIỂM TRA SLDAT CỦA CTDONDH PHẢI TỪ 30 ĐẾN 50
ALTER TABLE CTDONDH
ADD CONSTRAINT CK_CTDONDH_SLDAT
	CHECK (SLDAT BETWEEN 10 AND 50)
----------------------------------------------------------------
--XOÁ BẢNG NHACUNGCAP
DROP TABLE NHACUNGCAP

--XOÁ BẢNG VATTU
DROP TABLE VATTU

--XOÁ RÀNG BUỘC FK_CTDONDH_MAVTU KHỎI BẢNG CTDONDH
ALTER TABLE CTDONDH DROP CONSTRAINT FK_CTDONDH_MAVTU

--
ALTER TABLE CTDONDH NOCHECK CONSTRAINT CK_CTDONDH_SLDAT

ALTER TABLE CTDONDH CHECK CONSTRAINT CK_CTDONDH_SLDAT

--XOÁ DATABASE
USE MASTER
GO
DROP DATABASE QUANLYVATTU_B4_TH1

--
DECLARE @CharGender Char(1), @Gender Varchar(10)
SET @CharGender = 'M'
SET @Gender = CASE @CharGender
				WHEN 'M' THEN 'Male'
				ELSE 'Female'
				END
SELECT @Gender AS Gender