CREATE DATABASE QUANLYCUAHANGTHOITRANG_04
GO
USE QUANLYCUAHANGTHOITRANG_04

CREATE TABLE HANGSANXUAT (
	MAHSX VARCHAR(8) NOT NULL PRIMARY KEY,
	TENHSX NVARCHAR(50) NOT NULL,
	SODIENTHOAI VARCHAR(10) NOT NULL
)

CREATE TABLE SANPHAM (
	MASP VARCHAR(8) NOT NULL PRIMARY KEY,
	TENSP NVARCHAR(50) NOT NULL,
	MAUSAC NVARCHAR(10) NULL,
	GIANHAP FLOAT NOT NULL,
	GIABAN FLOAT NOT NULL,
	SIZE FLOAT NULL,
	SOLUONGCONCAI INT DEFAULT (0),
	MAHSX VARCHAR(8) NOT NULL
	FOREIGN KEY (MAHSX) REFERENCES HANGSANXUAT(MAHSX)
)

CREATE TABLE PHIEUMUAHANG (
	MADH VARCHAR(10) NOT NULL PRIMARY KEY,
	GIATIEN FLOAT NOT NULL,
	TONGTIEN FLOAT NOT NULL,
	TENNGUOIBAN NVARCHAR(20) NOT NULL,
	NGAYTAODON DATETIME DEFAULT (GETDATE())
)

CREATE TABLE NHANVIEN (
	MANV VARCHAR(10) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR(20) NOT NULL,
	NGAYVAOLAM DATETIME DEFAULT (GETDATE()),
	SONGAYLAMVIEC INT NULL
)

CREATE TABLE QUANLY (
	MAQL VARCHAR(10) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR(20) NOT NULL,
	NGAYVAOLAM DATETIME DEFAULT (GETDATE()),
	SONGAYLAMVIEC INT NULL
)

CREATE TABLE KHACHHANG (
	MAKH VARCHAR(10) NOT NULL PRIMARY KEY,
	TENKH NVARCHAR(20) NOT NULL,
	DIACHI NVARCHAR(30) NULL,
	SODIENTHOAI VARCHAR(30) NOT NULL
)