CREATE DATABASE QUANLYCUAHANGTHOITRANG
GO
USE QUANLYCUAHANGTHOITRANG
GO

CREATE TABLE LOAIMATHANG (
  MALOAI VARCHAR(10) PRIMARY KEY,
  TENLOAI NVARCHAR(30)
)
GO
CREATE TABLE MATHANG (
  MAMH VARCHAR(10) PRIMARY KEY,
  TENMH NVARCHAR(30),
  QUYCACH VARCHAR(10),
  GIABAN FLOAT,
  MALOAI VARCHAR(10),
  FOREIGN KEY (MALOAI) REFERENCES LOAIMATHANG (MALOAI)
)
GO

CREATE TABLE PHIEUDONGHANG (
  MAPDH VARCHAR(10) PRIMARY KEY,
  NGAYDONG DATE,
  MAMH VARCHAR(10),
  FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
)

CREATE TABLE NGUYENVATLIEU (
  MANVL VARCHAR(10) PRIMARY KEY,
  TENNVL NVARCHAR(30)
)

CREATE TABLE NHANVIEN (
  MANV VARCHAR(10) PRIMARY KEY,
  HOTEN NVARCHAR(50)
)

CREATE TABLE NHACUNGCAP (
  MANCC VARCHAR(10) PRIMARY KEY,
  TENNCC NVARCHAR(50),
  DIACHI NVARCHAR(100),
  SODIENTHOAI VARCHAR(10)
)

CREATE TABLE KHACHHANG (
  MAKH VARCHAR(10) PRIMARY KEY,
  TENKH NVARCHAR(50),
  DIACHI NVARCHAR(100),
  SODIENTHOAI VARCHAR(10)
)

CREATE TABLE NHAPNGUYENVATLIEU (
  SOPHIEU VARCHAR(10) PRIMARY KEY,
  NGAYLAPPHIEU DATE,
  MANCC VARCHAR(10),
  FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
)

CREATE TABLE HOADONBANHANG (
  SOHD VARCHAR(10) PRIMARY KEY,
  NGAYLAP DATE,
  MAKH VARCHAR(10),
  FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CTPHIEUNHAP (
  SOPHIEU VARCHAR(10),
  MANVL VARCHAR(10),
  SOLUONG INT,
  DONGGIA FLOAT,
  PRIMARY KEY (SOPHIEU, MANVL),
  FOREIGN KEY (SOPHIEU) REFERENCES NHAPNGUYENVATLIEU(SOPHIEU),
  FOREIGN KEY (MANVL) REFERENCES NGUYENVATLIEU(MANVL)
)

CREATE TABLE CTPHIEUDONG (
  MAPDH VARCHAR(10),
  MANVL VARCHAR(10),
  SOLUONG INT,
  PRIMARY KEY (MAPDH, MANVL),
  FOREIGN KEY (MAPDH) REFERENCES PHIEUDONGHANG(MAPDH),
  FOREIGN KEY (MANVL) REFERENCES NGUYENVATLIEU(MANVL)
)

CREATE TABLE THAMGIADONGHANG (
  MAPDH VARCHAR(10),
  MANV VARCHAR(10),
  PRIMARY KEY (MAPDH, MANV),
  FOREIGN KEY (MAPDH) REFERENCES PHIEUDONGHANG(MAPDH),
  FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE CTHOADON (
  SOHD VARCHAR(10),
  MAMH VARCHAR(10),
  SOLUONG INT,
  GIABAN FLOAT,
  PRIMARY KEY (SOHD, MAMH),
  FOREIGN KEY (SOHD) REFERENCES HOADONBANHANG(SOHD),
  FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
)

DROP DATABASE QUANLYCUAHANGTHOITRANG