/*********************CREATE DATABASE********************************/
CREATE DATABASE QUANLYNHANVIEN_B9_2574802010111
GO 
USE QUANLYNHANVIEN_B9_2574802010111

/************************TAO BANG NHAN VIEN QUAN LY DO AN*************************/
CREATE TABLE NHANVIEN(HONV NVARCHAR(15) NOT NULL,
						TENLOT NVARCHAR(15) NOT NULL,
						   TENNV NVARCHAR(15) NOT NULL,
							  MANV VARCHAR(9) NOT NULL,
								 NGSINH DATE NULL,
									DCHI NVARCHAR(100) NULL,
									  PHAI NVARCHAR(3) NOT NULL,
										 LUONG INT NULL,
											MA_NQL VARCHAR(9) NULL,
												PHG INT NULL)

/***************************TAO BANG QUAN LY PHONG BAN ***************************/			                        
CREATE TABLE PHONGBAN(TENPHG NVARCHAR(15) NOT NULL,
						MAPHG INT NOT NULL,
						   TRPHG VARCHAR(9) NOT NULL,
							  NG_NHANCHUC DATE NOT NULL)

/******************************DIA DIEM CUA PHONG BAN*****************************/
CREATE TABLE DIADIEM_PHG(MAPHG INT NOT NULL,
							DIADIEM NVARCHAR(30) NOT NULL)

/*****************************TAO BANG PHAN CONG ********************************/
CREATE TABLE PHANCONG(MA_NVIEN VARCHAR(9) NOT NULL,
						 SODA INT NOT NULL,
 							 THOIGIAN FLOAT NULL)

/*******************************TAO BANG THANH NHAN ****************************/
CREATE TABLE THANNHAN(MA_NVIEN VARCHAR(9) NOT NULL,
						 TENTN NVARCHAR(50) NOT NULL,
							PHAI NVARCHAR(3) NOT NULL,
								NGSINH DATE NULL,
									QUANHE NVARCHAR(30) NOT NULL)

/***********************************TAO BANG DE AN****************************/
CREATE TABLE DEAN(TENDA NVARCHAR(30) NOT NULL,
					 MADA INT NOT NULL,
						DDIEM_DA NVARCHAR(30) NOT NULL,
							PHONG INT  NULL)

/***********************************TAO KHOA CHINH****************************/
ALTER TABLE NHANVIEN 
ADD CONSTRAINT PK_NHANVIEN
PRIMARY KEY (MANV)

ALTER TABLE PHONGBAN ADD CONSTRAINT PK_PHONGBAN
PRIMARY KEY (MAPHG)

ALTER TABLE DIADIEM_PHG ADD CONSTRAINT PK_DIADIEM_PHG
PRIMARY KEY (MAPHG, DIADIEM)

ALTER TABLE DEAN ADD CONSTRAINT PK_DEAN
PRIMARY KEY (MADA)

ALTER TABLE PHANCONG ADD CONSTRAINT PK_PHANCONG
PRIMARY KEY (MA_NVIEN, SODA)

ALTER TABLE THANNHAN ADD CONSTRAINT PK_THANNHAN
PRIMARY KEY (MA_NVIEN, TENTN)

/***********************************TAO KHOA NGOAI****************************/
ALTER TABLE PHONGBAN
ADD CONSTRAINT FK_PHONGBAN_TRPHG
FOREIGN KEY (TRPHG) REFERENCES NHANVIEN(MANV)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_MA_NQL
FOREIGN KEY (MA_NQL) REFERENCES NHANVIEN(MANV),
CONSTRAINT FK_NHANVIEN_PHG
FOREIGN KEY (PHG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE DIADIEM_PHG
ADD CONSTRAINT FK_DIADIEM_PHG_MAPHG
FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE DEAN
ADD CONSTRAINT FK_DEAN_PHONG
FOREIGN KEY (PHONG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_MA_NVIEN
FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV),
CONSTRAINT FK_PHANCONG_SODA
FOREIGN KEY (SODA) REFERENCES DEAN(MADA)

ALTER TABLE THANNHAN
ADD CONSTRAINT FK_THANNHAN_MA_NVIEN
FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV)

/*********************DROP DATABASE***********************************/
drop table NHANVIEN
drop table PHONGBAN
drop table DIADIEM_PHG
drop table PHANCONG
drop table THANNHAN
drop table DEAN 

go
use master

drop database QUANLYNHANVIEN_B9_2574802010111

/***************************USE DATABASE***********************************/
-- 1. Bang NHANVIEN
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG) VALUES (N'Đinh', N'Bá', N'Tiến', 'NV001', '1995-09-01', N'731 Trần Hưng Đạo, Q1, TP HCM', N'Nam', 30000, 'NV002', 5)
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG) VALUES (N'Nguyễn', N'Thanh', N'Tùng', 'NV002', '1996-08-12', N'638 Nguyễn Văn Cừ, Q5, TP HCM', N'Nam', 40000, 'NV008', 5)
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG) VALUES (N'Bùi', N'Ngọc', N'Hằng', 'NV003', '1997-07-19', N'332 Nguyễn Thái Học, Q1, TP HCM', N'Nữ', 25000, 'NV004', 4)
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG) VALUES (N'Lê', N'Quỳnh', N'Như', 'NV004', '1998-06-20', N'291 Hồ Văn Huê, QPN, TP HCM', N'Nữ', 43000, 'NV008', 4)
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG) VALUES (N'Nguyễn', N'Mạnh', N'Hùng', 'NV005', '1999-09-15', N'975 Bà Rịa, Vũng Tàu', N'Nam', 38000, 'NV002', 5)
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG) VALUES (N'Trần', N'Thanh', N'Tâm', 'NV006', '2000-07-31', N'543 Mai Thị Lựu, Q1, TP HCM', N'Nữ', 25000, 'NV002', 5)
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG) VALUES (N'Trần', N'Hồng', N'Quang', 'NV007', '1996-03-09', N'980 Lê Hồng Phong, Q10, TP HCM', N'Nam', 25000, 'NV004', 4)
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG) VALUES (N'Phạm', N'Văn', N'Vinh', 'NV008', '1997-11-10', N'450 Trưng Vương, Hà Nội', N'Nam', 55000, NULL, 1)

-- 2. Bang PHONGBAN
INSERT INTO PHONGBAN (TENPHG, MAPHG, TRPHG, NG_NHANCHUC) VALUES (N'Nghiên cứu', 5, 'NV002', '2020-05-22')
INSERT INTO PHONGBAN (TENPHG, MAPHG, TRPHG, NG_NHANCHUC) VALUES (N'Điều hành', 4, 'NV007', '2022-01-01')
INSERT INTO PHONGBAN (TENPHG, MAPHG, TRPHG, NG_NHANCHUC) VALUES (N'Quản lý', 1, 'NV008', '2025-06-19')

-- 3. Bang DIADIEM_PHG
INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM) VALUES (1, N'TP HCM')
INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM) VALUES (4, N'Hà Nội')
INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM) VALUES (5, N'Vũng Tàu')
INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM) VALUES (5, N'Nha Trang')
INSERT INTO DIADIEM_PHG (MAPHG, DIADIEM) VALUES (5, N'TP HCM')

-- 4. Bang DEAN
INSERT INTO DEAN (TENDA, MADA, DDIEM_DA, PHONG) VALUES (N'Sản phẩm X', 1, N'Vũng Tàu', 5)
INSERT INTO DEAN (TENDA, MADA, DDIEM_DA, PHONG) VALUES (N'Sản phẩm Y', 2, N'Nha Trang', 5)
INSERT INTO DEAN (TENDA, MADA, DDIEM_DA, PHONG) VALUES (N'Sản phẩm Z', 3, N'TP HCM', 5)
INSERT INTO DEAN (TENDA, MADA, DDIEM_DA, PHONG) VALUES (N'Tin học hóa', 10, N'Hà Nội', 4)
INSERT INTO DEAN (TENDA, MADA, DDIEM_DA, PHONG) VALUES (N'Cáp quang', 20, N'TP HCM', 1)
INSERT INTO DEAN (TENDA, MADA, DDIEM_DA, PHONG) VALUES (N'Đào tạo', 30, N'Hà Nội', 4)

-- 5. Bang PHANCONG
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV001', 1, 32.5)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV001', 2, 7.5)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV005', 3, 40)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV006', 1, 20)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV006', 2, 20)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV002', 2, 10)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV002', 3, 10)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV002', 10, 10)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV002', 20, 10)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV003', 30, 30)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV003', 10, 10)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV007', 10, 35)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV007', 30, 5)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV004', 30, 20)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV004', 20, 15)
INSERT INTO PHANCONG (MA_NVIEN, SODA, THOIGIAN) VALUES ('NV008', 20, NULL)

-- 6. Bang THANNHAN
INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('NV002', N'Nguyễn Trinh', N'Nữ', '2022-04-05', N'Con gái')
INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('NV002', N'Nguyễn Khang', N'Nam', '2025-10-25', N'Con trai')
INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('NV002', N'Pham Phuong', N'Nữ', '1996-05-03', N'Vợ chồng')
INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('NV004', N'Lê Minh', N'Nam', '1998-02-28', N'Vợ chồng')
INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('NV001', N'Đinh Tiến', N'Nam', '2023-01-01', N'Con trai')
INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('NV001', N'Đinh Châu', N'Nữ', '2024-12-30', N'Con gái')
INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('NV001', N'Nguyễn Phương', N'Nữ', '1995-05-05', N'Vợ chồng')

/***************************TRUY XUAT CAC BANG **************************/
SELECT * FROM NHANVIEN	
SELECT * FROM PHONGBAN
SELECT * FROM DIADIEM_PHG 
SELECT * FROM DEAN
SELECT * FROM PHANCONG
SELECT * FROM THANNHAN

/*****************************CAC CAU TRUY VAN**************************/
--Phép kết:
--1. Hãy hiển thị Mã nhân viên (MANV), Tên nhân viên (TENNV) và Tên phòng ban (TENPHG) của tất cả nhân viên nam có mức lương trên 35,000 thuộc phòng ban số 5.
SELECT N.MANV, N.TENNV, P.TENPHG
FROM NHANVIEN N JOIN PHONGBAN P ON N.PHG = P.MAPHG
WHERE N.PHAI = N'Nam' AND N.LUONG > 35000 AND N.PHG = 5

--2. Hãy xuất ra Mã nhân viên (MANV), Tên nhân viên (TENNV), Tên đề án (TENDA) và Thời gian (THOIGIAN) của những nhân viên họ 'Nguyễn' 
--tham gia vào các đề án với tổng thời gian làm việc được phân công nằm trong khoảng từ 15 đến 35 giờ.
SELECT N.MANV, N.TENNV, SUM(PC.THOIGIAN) AS TONGTHOIGIAN
FROM NHANVIEN N JOIN PHANCONG PC ON N.MANV = PC.MA_NVIEN
WHERE N.HONV = N'Nguyễn'
GROUP BY N.MANV, N.TENNV
HAVING SUM(PC.THOIGIAN) BETWEEN 15 AND 35

--Truy vấn lồng:
--3. Hãy cho biết mã nhân viên, tên nhân viên, ngày sinh của những nhân viên có lương cao nhất.
SELECT MANV, TENNV, NGSINH FROM NHANVIEN
WHERE LUONG >= ALL (SELECT LUONG FROM NHANVIEN)

--4. Hãy cho biết mã đề án, tên đề án có thời gian phân công trung bình là thấp nhất.
SELECT DA.MADA, DA.TENDA
FROM PHANCONG PC JOIN DEAN DA ON PC.SODA = DA.MADA
GROUP BY DA.MADA, DA.TENDA
HAVING AVG(PC.THOIGIAN) <= ALL (SELECT AVG(THOIGIAN) FROM PHANCONG GROUP BY SODA)

--5. Hãy cho biết mã nhân viên, tên nhân viên tham gia nhiều đề án nhất.
SELECT MANV, TENNV
FROM NHANVIEN N JOIN PHANCONG P ON N.MANV = P.MA_NVIEN
GROUP BY N.MANV, N.TENNV
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM PHANCONG GROUP BY MA_NVIEN)

--6. Hãy cho biết mã phòng ban, tên phòng ban của phòng ban nào không có nhân viên Nữ.
SELECT MAPHG, TENPHG FROM PHONGBAN
WHERE MAPHG NOT IN (SELECT PHG FROM NHANVIEN WHERE PHAI = N'Nữ')