/**********************************USE DATABASE********************************/

GO
USE QUANLYDAOTAO_B9_2574802010111

INSERT INTO KHOA VALUES('CNTT',N'Công Nghệ Thông Tin',1995)
	INSERT INTO KHOA VALUES('VL',N'Vật Lý',2005)
		INSERT INTO KHOA VALUES('TOAN',N'Toán',1976)

INSERT INTO SVIEN VALUES(N'Sơn',17,1,'CNTT')
	INSERT INTO SVIEN VALUES(N'Bảo',8,2,'CNTT')
		INSERT INTO SVIEN VALUES(N'Trang',5,3,'TOAN')
		
INSERT INTO MHOC VALUES(N'Nhập Môn Tin Học','COSC1310',4,'CNTT')
	INSERT INTO MHOC VALUES(N'Cấu Trúc Dữ Liệu','COSC3320',4,'CNTT')	
		INSERT INTO MHOC VALUES(N'Toán Rời Rạc','MATH2410',3,'TOAN')
			INSERT INTO MHOC VALUES(N'Cơ Sở Dữ Liệu','COSC3380',3,'CNTT')
				INSERT INTO MHOC VALUES(N'Vật Lý Đại Cương','PHYS3332',3,'VL')

INSERT INTO DKIEN VALUES('COSC3380','COSC3320')
	INSERT INTO DKIEN VALUES('COSC3380','MATH2410')
		INSERT INTO DKIEN VALUES('COSC3320','COSC1310')

INSERT INTO HPHAN VALUES(85,'MATH2410',1,1996,N'Kim')
	INSERT INTO HPHAN VALUES(92,'COSC1310',1,1996,N'An')
		INSERT INTO HPHAN VALUES(102,'COSC3320',2,1997,N'Nhiên')
			INSERT INTO HPHAN VALUES(112,'MATH2410',1,1997,NULL)
				INSERT INTO HPHAN VALUES(119,'COSC1310',1,1997,N'An')
					INSERT INTO HPHAN VALUES(135,'COSC3380',1,1997,N'Sơn')

INSERT INTO KQUA VALUES(17,102,8)
	INSERT INTO KQUA VALUES(17,119,6)
		INSERT INTO KQUA VALUES(5,85,10)
			INSERT INTO KQUA VALUES(8,92,10)
				INSERT INTO KQUA VALUES(8,102,8)
					INSERT INTO KQUA VALUES(8,135,10)
/****************************HAM XUAT*********************************/
SELECT * FROM SVIEN 
SELECT * FROM DKIEN
SELECT * FROM KHOA 
SELECT * FROM MHOC 
SELECT * FROM HPHAN 
SELECT * FROM KQUA 

/****************************TRUY VAN DU LIEU************************/
--Phép kết:
--1. Hãy hiển thị danh sách tất cả các sinh viên cùng với thông tin khoa mà họ đang theo học. 
--Kết quả cần hiển thị các cột: Mã sinh viên (MASV), Tên sinh viên (TEN), Tên khoa (TENKHOA), và Năm thành lập khoa (NAMTHANHLAP) và 
--chỉ hiển thị những sinh viên thuộc các khoa được thành lập trước năm 2000.
SELECT MASV, TEN, TENKHOA, NAMTHANHLAP
FROM SVIEN S INNER JOIN KHOA K ON S.MAKH = K.MAKHOA
WHERE K.NAMTHANHLAP < 2000

--2. Hãy hiển thị danh sách gồm các thông tin: Tên sinh viên (TEN), Tên môn học (TENMH), và Điểm số (DIEM) 
--và chỉ lọc ra những sinh viên có kết quả điểm số từ 8.0 trở lên
SELECT S.TEN, M.TENMH, KQ.DIEM
FROM SVIEN S INNER JOIN KQUA KQ ON S.MASV = KQ.MASV
INNER JOIN HPHAN HP ON KQ.MAHP = HP.MAHP
INNER JOIN MHOC M ON HP.MAMH = M.MAMH
WHERE KQ.DIEM >= 8

--Truy vấn lồng:
--3. Hãy cho biết mã môn học, tên môn học có số tín chỉ lớn nhất.
SELECT MAMH, TENMH FROM MHOC
WHERE TINCHI = (SELECT MAX(TINCHI) FROM MHOC)
--
SELECT MAMH, TENMH FROM MHOC
WHERE TINCHI >= ALL (SELECT TINCHI FROM MHOC)

--4. Hãy cho biết mã học phần, mã môn học và học kỳ của học phần mà chưa có kết quả.
SELECT HP.MAHP, M.MAMH, HP.HOCKY
FROM HPHAN HP INNER JOIN MHOC M ON HP.MAMH = M.MAMH
WHERE HP.MAHP NOT IN (SELECT MAHP FROM KQUA)
--
SELECT HP.MAHP, M.MAMH, HP.HOCKY
FROM HPHAN HP INNER JOIN MHOC M ON HP.MAMH = M.MAMH
WHERE NOT EXISTS (SELECT MAHP FROM KQUA K WHERE HP.MAHP = K.MAHP)

--5. Hãy cho biết mã khoa, tên khoa có đông sinh viên nhất.
SELECT K.MAKHOA, K.TENKHOA
FROM KHOA K, SVIEN S
WHERE K.MAKHOA = S.MAKH
GROUP BY K.MAKHOA, K.TENKHOA
HAVING COUNT(*) >= ALL(SELECT COUNT(*) FROM SVIEN GROUP BY MAKH)

--6. Hãy cho biết mã sinh viên có điểm trung bình tích lũy thấp nhất.
SELECT K.MASV FROM KQUA K, SVIEN S
WHERE S.MASV = K.MASV
GROUP BY K.MASV
HAVING AVG(DIEM) <= ALL (SELECT AVG(DIEM) FROM KQUA GROUP BY MASV)
