/******************************CREATE DATABASE********************************/

CREATE DATABASE QUANLYSINHVIEN_B3_2574802010111
GO 
USE QUANLYSINHVIEN_B3_2574802010111

/************************TAO BANG KHOA QUAN LY SINH VIEN*************************/
CREATE TABLE KHOA(MAKHOA VARCHAR(4) NOT NULL ,
			TENKHOA NVARCHAR(30) NOT NULL,
			      NAMTHANHLAP INT NOT NULL) 

/************************TAO BANG SVIEN QUAN LY SINH VIEN*************************/
CREATE TABLE SVIEN(TEN NVARCHAR(30) NOT NULL,
			MASV INT NOT NULL,
			   NAM INT NOT NULL,
				 NGAYSINH DATE NULL,
			      MAKH VARCHAR(4) NOT NULL)

/************************TAO BANG MHOC QUAN LY SINH VIEN*************************/
CREATE TABLE MHOC(TENMH NVARCHAR(30) NOT NULL,
			MAMH VARCHAR(8) NOT NULL,
			   TINCHI INT NOT NULL,
			      MAKH VARCHAR(4) NOT NULL)

/************************TAO BANG DKIEN QUAN LY SINH VIEN*************************/
CREATE TABLE DKIEN(MAMH VARCHAR(8) NOT NULL,
			MAMH_TRUOC VARCHAR(8) NOT NULL
			)


/************************TAO BANG HPHAN QUAN LY SINH VIEN*************************/
CREATE TABLE HPHAN(MAHP INT NOT NULL,
			MAMH VARCHAR(8) NOT NULL,
			   HOCKY VARCHAR(5) NOT NULL,
			      NAM INT NOT NULL,
					GV NVARCHAR(30) NULL, 
						NGAYBD DATE, 
							NGAYKT DATE
			)

/************************TAO BANG KQUA QUAN LY SINH VIEN*************************/
CREATE TABLE KQUA(MASV INT NOT NULL,
			   MAHP INT NOT NULL,
			      DIEM FLOAT NOT NULL
			)

/*****************************************************************************/
ALTER TABLE KHOA
ADD CONSTRAINT PK_KHOA
PRIMARY KEY (MAKHOA)

ALTER TABLE SVIEN 
ADD CONSTRAINT PK_SVIEN
	PRIMARY KEY (MASV)

ALTER TABLE SVIEN
ADD CONSTRAINT FK_SVIEN_MAKH
	FOREIGN KEY (MAKH)
	REFERENCES KHOA (MAKHOA)

ALTER TABLE MHOC
ADD CONSTRAINT PK_MHOC
PRIMARY KEY (MAMH)

ALTER TABLE MHOC
ADD CONSTRAINT FK_MHOC_MAKH
FOREIGN KEY (MAKH)
REFERENCES KHOA(MAKHOA)

ALTER TABLE DKIEN
ADD CONSTRAINT PK_DKIEN
PRIMARY KEY (MAMH, MAMH_TRUOC)

ALTER TABLE DKIEN
ADD CONSTRAINT FK_DKIEN_MAMH
FOREIGN KEY (MAMH)
REFERENCES MHOC(MAMH)

ALTER TABLE DKIEN
ADD CONSTRAINT FK_DKIEN_MAMH_TRUOC
FOREIGN KEY (MAMH_TRUOC)
REFERENCES MHOC(MAMH)

ALTER TABLE HPHAN
ADD CONSTRAINT PK_HPHAN
PRIMARY KEY (MAHP)

ALTER TABLE HPHAN
ADD CONSTRAINT FK_HPHAN_MAMH
FOREIGN KEY (MAMH)
REFERENCES MHOC(MAMH)

ALTER TABLE KQUA
ADD CONSTRAINT PK_KQUA
	PRIMARY KEY (MASV, MAHP)

ALTER TABLE KQUA 
ADD CONSTRAINT FK_KQUA_MASV
	FOREIGN KEY (MASV)
	REFERENCES SVIEN (MASV)

ALTER TABLE KQUA 
ADD CONSTRAINT FK_KQUA_MAHP
	FOREIGN KEY (MAHP)
	REFERENCES HPHAN (MAHP)

/***********************************ALTER***********************************/
--1. Thêm một ràng buộc thiết lập giá trị mặc định là 1 cho cột NAM (Năm thứ) của bảng SVIEN (Sinh viên)
ALTER TABLE SVIEN ADD CONSTRAINT DF_SVIEN_NAM DEFAULT 1 FOR NAM

--2. Thêm ràng buộc kiểm tra cột TINCHI (Tín chỉ) trong bảng MHOC (Môn học) là một số lớn hơn bằng 1.
ALTER TABLE MHOC ADD CONSTRAINT CK_MHOC_TINCHI CHECK (TINCHI >= 1)

--3. Thêm ràng buộc kiểm tra cột MAKHOA (Mã khoa) trong bảng KHOA (Khoa) phải bắt đầu bằng 1 ký tự ‘K’.
ALTER TABLE KHOA ADD CONSTRAINT CK_KHOA_MAKHOA CHECK (MAKHOA LIKE 'K%')

--4. Thêm ràng buộc kiểm tra cột HOCKY (Học kỳ) trong bảng HPHAN (Học phần) phải là một trong các giá trị (1, 2, 3, 4, 5, 6, 7, 8, 9).
ALTER TABLE HPHAN ADD CONSTRAINT CK_HPHAN_HOCKY CHECK (HOCKY IN ('1', '2', '3', '4', '5', '6', '7', '8', '9'))

--5. Thêm ràng buộc kiểm tra cột MAMH (Mã môn học) trong bảng MHOC (Môn học) phải có 2 ký tự tận cùng là ‘MH’.
ALTER TABLE MHOC ADD CONSTRAINT CK_MHOC_MAMH CHECK (MAMH LIKE '%MH')

--6. Thêm ràng buộc kiểm tra tuổi của sinh viên phải từ 17 trở lên (lưu ý: tuổi được tính từ cột NGAYSINH (Ngày sinh) trong bảng SVIEN (Sinh viên)).
ALTER TABLE SVIEN ADD CONSTRAINT CK_SVIEN_TUOI CHECK (DATEDIFF(YEAR, NGAYSINH, GETDATE()) >= 17)