--1. Tạo Database QUANLYDAOTAO_B2_MSSV (MSSV thay bằng mã số của Sinh viên).
CREATE DATABASE QUANLYDAOTAO_B2_2574802010111
GO
USE QUANLYDAOTAO_B2_2574802010111
GO

--2. Tạo 3 Table KHOA, SVIEN và MHOC theo kiểu dữ liệu trên.
--TẠO BẢNG KHOA
CREATE TABLE KHOA (
	MAKHOA VARCHAR(4) NOT NULL,
	TENKHOA NVARCHAR(30) NOT NULL,
	NAMTHANHLAP INT NULL
)
--TẠO BẢNG SVIEN
CREATE TABLE SVIEN (
	HOTEN NVARCHAR(30) NOT NULL,
	MASV INT NOT NULL,
	NAM INT NULL,
	MAKH VARCHAR(4) NOT NULL
)
--TẠO BẢNG MHOC
CREATE TABLE MHOC (
	TENMH NVARCHAR(30) NOT NULL,
	MAMH VARCHAR(8) NOT NULL,
	TINCHI INT NOT NULL,
	MAKH VARCHAR(4) NOT NULL
)

--3. Tạo tất cả các khóa chính có thể có bằng câu lệnh Alter.
--TẠO KHÓA CHÍNH CỦA KHOA
ALTER TABLE KHOA
ADD CONSTRAINT PK_KHOA
PRIMARY KEY (MAKHOA)
--TẠO KHÓA CHÍNH CỦA SVIEN
ALTER TABLE SVIEN
ADD CONSTRAINT PK_SVIEN
PRIMARY KEY (MASV)
--TẠO KHÓA CHÍNH CỦA MHOC
ALTER TABLE MHOC
ADD CONSTRAINT PK_MHOC
PRIMARY KEY (MAMH)

--4. Tạo tất cả các khóa ngoại có thể có bằng câu lệnh Alter.
--TẠO KHÓA NGOẠI CỦA SVIEN
ALTER TABLE SVIEN
ADD CONSTRAINT FK_SVIEN_MAKH
FOREIGN KEY (MAKH) REFERENCES KHOA(MAKHOA)
--TẠO KHÓA NGOẠI CỦA MHOC
ALTER TABLE MHOC
ADD CONSTRAINT FK_MHOC_MAKH
FOREIGN KEY (MAKH) REFERENCES KHOA(MAKHOA)

--5. Thay đổi thuộc tính TEN (tên) của bảng SVIEN như sau:
--Column Name Data type Allow Nulls
--HOTEN NVARCHAR(50) NULL
ALTER TABLE SVIEN ALTER COLUMN HOTEN NVARCHAR(50) NULL

--6. Bổ sung ràng buộc cho bảng MHOC để đảm bảo rằng TENMH (Tên môn học) phải là duy nhất không trùng.
ALTER TABLE MHOC ADD CONSTRAINT UQ_MHOC_TENMH UNIQUE (TENMH)

--7. Hãy Xóa cột NAMTHANHLAP (năm thành lập) khỏi bảng KHOA.
ALTER TABLE KHOA DROP COLUMN NAMTHANHLAP