/******************************CREATE DATABASE********************************/

CREATE DATABASE QUANLYSINHVIEN_B3_2_2574802010111
GO 
USE QUANLYSINHVIEN_B3_2_2574802010111

/************************TAO BANG KHOA QUAN LY SINH VIEN*************************/
CREATE TABLE KHOA(MAKHOA VARCHAR(4) NOT NULL ,
			TENKHOA NVARCHAR(30) NOT NULL,
			      NAMTHANHLAP INT NOT NULL) 

/************************TAO BANG SVIEN QUAN LY SINH VIEN*************************/
CREATE TABLE SVIEN(TEN NVARCHAR(30) NOT NULL,
			MASV INT NOT NULL,
			   NAM INT NOT NULL,
				 NGAYSINH DATE NULL,
			      MAKH VARCHAR(4) NOT NULL)

/************************TAO BANG MHOC QUAN LY SINH VIEN*************************/
CREATE TABLE MHOC(TENMH NVARCHAR(30) NOT NULL,
			MAMH VARCHAR(8) NOT NULL,
			   TINCHI INT NOT NULL,
			      MAKH VARCHAR(4) NOT NULL)

/************************TAO BANG DKIEN QUAN LY SINH VIEN*************************/
CREATE TABLE DKIEN(MAMH VARCHAR(8) NOT NULL,
			MAMH_TRUOC VARCHAR(8) NOT NULL
			)


/************************TAO BANG HPHAN QUAN LY SINH VIEN*************************/
CREATE TABLE HPHAN(MAHP INT NOT NULL,
			MAMH VARCHAR(8) NOT NULL,
			   HOCKY VARCHAR(5) NOT NULL,
			      NAM INT NOT NULL,
					GV NVARCHAR(30) NULL, 
						NGAYBD DATE, 
							NGAYKT DATE
			)

/************************TAO BANG KQUA QUAN LY SINH VIEN*************************/
CREATE TABLE KQUA(MASV INT NOT NULL,
			   MAHP INT NOT NULL,
			      DIEM FLOAT NOT NULL
			)

/*****************************************************************************/
ALTER TABLE KHOA
ADD CONSTRAINT PK_KHOA
PRIMARY KEY (MAKHOA)

ALTER TABLE SVIEN 
ADD CONSTRAINT PK_SVIEN
	PRIMARY KEY (MASV)

ALTER TABLE SVIEN
ADD CONSTRAINT FK_SVIEN_MAKH
	FOREIGN KEY (MAKH)
	REFERENCES KHOA (MAKHOA)

ALTER TABLE MHOC
ADD CONSTRAINT PK_MHOC
PRIMARY KEY (MAMH)

ALTER TABLE MHOC
ADD CONSTRAINT FK_MHOC_MAKH
FOREIGN KEY (MAKH)
REFERENCES KHOA(MAKHOA)

ALTER TABLE DKIEN
ADD CONSTRAINT PK_DKIEN
PRIMARY KEY (MAMH, MAMH_TRUOC)

ALTER TABLE DKIEN
ADD CONSTRAINT FK_DKIEN_MAMH
FOREIGN KEY (MAMH)
REFERENCES MHOC(MAMH)

ALTER TABLE DKIEN
ADD CONSTRAINT FK_DKIEN_MAMH_TRUOC
FOREIGN KEY (MAMH_TRUOC)
REFERENCES MHOC(MAMH)

ALTER TABLE HPHAN
ADD CONSTRAINT PK_HPHAN
PRIMARY KEY (MAHP)

ALTER TABLE HPHAN
ADD CONSTRAINT FK_HPHAN_MAMH
FOREIGN KEY (MAMH)
REFERENCES MHOC(MAMH)

ALTER TABLE KQUA
ADD CONSTRAINT PK_KQUA
	PRIMARY KEY (MASV, MAHP)

ALTER TABLE KQUA 
ADD CONSTRAINT FK_KQUA_MASV
	FOREIGN KEY (MASV)
	REFERENCES SVIEN (MASV)

ALTER TABLE KQUA 
ADD CONSTRAINT FK_KQUA_MAHP
	FOREIGN KEY (MAHP)
	REFERENCES HPHAN (MAHP)

/***********************************ALTER***********************************/
--1. Thêm một ràng buộc thiết lập giá trị mặc định là 3 cho cột TINCHI (Tín chỉ) của bảng MHOC (Môn học).
ALTER TABLE MHOC ADD CONSTRAINT DF_MHOC_TINCHI DEFAULT 3 FOR TINCHI

--2. Thêm ràng buộc kiểm tra cột NAM (Năm thứ) trong bảng SVIEN (Sinh viên) là một trong các giá trị (1, 2, 3, 4).
ALTER TABLE SVIEN ADD CONSTRAINT CK_SVIEN_NAM CHECK (NAM IN (1, 2, 3, 4))

--3. Thêm ràng buộc kiểm tra cột MAMH (Mã môn học) trong bảng MHOC (Môn học) phải bắt đầu bằng 2 ký tự ‘MH’.
ALTER TABLE MHOC ADD CONSTRAINT CK_MHOC_MAMH CHECK (MAMH LIKE 'MH%')

--4. Thêm ràng buộc kiểm tra cột DIEM (Điểm) của bảng KQUA (Kết quả) phải từ 0 đến 10.
ALTER TABLE KQUA ADD CONSTRAINT CK_KQUA_DIEM CHECK (DIEM BETWEEN 0 AND 10)

--5. Thêm ràng buộc kiểm tra cột MAKHOA (Mã khoa) trong bảng KHOA (Khoa) phải có 2 ký tự ‘KH’ trong mã (nằm đâu cũng được).
ALTER TABLE KHOA ADD CONSTRAINT CK_KHOA_MAKHOA CHECK (MAKHOA LIKE '%KH%')

--6. Thêm ràng buộc kiểm tra cột NGAYKT (Ngày kết thúc) phải lớn hơn NGAYBD (Ngày bắt đầu) của bảng HPHAN (Học phần).
ALTER TABLE HPHAN ADD CONSTRAINT CK_HPHAN_NGAYKT CHECK (NGAYKT > NGAYBD)
