CREATE DATABASE QUANLYPHONGBAN
GO
USE QUANLYPHONGBAN
GO

CREATE TABLE PHONGBAN(
	TENPHG NVARCHAR(50) NULL,
	MAPHG VARCHAR(10) NOT NULL,
	NGAY_NHANCHUC DATE NULL,
)

CREATE TABLE DEAN(
	TENDA NVARCHAR(100) NOT NULL,
    MADA VARCHAR(10) NOT NULL,
    DDIEM_DA NVARCHAR(50) NULL,
    PHONG VARCHAR(10) NULL
)

CREATE TABLE NHANVIEN(
    HOTEN NVARCHAR(20) NULL,
    MANV VARCHAR(10) NOT NULL,
    NGSINH DATE NULL,
    DCHI NVARCHAR(100) NOT NULL,
    LUONG INT NOT NULL,
    PHG VARCHAR(10) NULL
)

ALTER TABLE PHONGBAN
ADD CONSTRAINT PK_PHONGBAN_MAPHG
PRIMARY KEY (MAPHG)

ALTER TABLE DEAN
ADD CONSTRAINT PK_DEAN_MADA
PRIMARY KEY (MADA)

ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN_MANV
PRIMARY KEY (MANV)

ALTER TABLE DEAN
ADD CONSTRAINT FK_DEAN_PHONG
FOREIGN KEY (PHONG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_PHG
FOREIGN KEY (PHG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE DEAN
ALTER COLUMN DDIEM_DA NVARCHAR(100) NULL

ALTER TABLE DEAN
ADD CONSTRAINT UQ_DEAN_TENDA
UNIQUE (TENDA)

ALTER TABLE PHONGBAN
ADD SOLUONGNV INT NULL