CREATE DATABASE QUANLYMATHANG_B2_2574802010111
GO
USE QUANLYMATHANG_B2_2574802010111
GO

CREATE TABLE LOAIHANG(
	MALH VARCHAR(4) NOT NULL,
	TENLH NVARCHAR(20) NOT NULL
)

CREATE TABLE NHACUNGCAP(
	  MACONGTY VARCHAR(4) NOT NULL,
    TENCONGTY NVARCHAR(30) NULL,
    DIACHI NVARCHAR(50) NULL,
    DIENTHOAI VARCHAR(15) NULL
)

CREATE TABLE MATHANG(
    MAHANG VARCHAR(4) NOT NULL,
    TENHANG NVARCHAR(30) NOT NULL,
    MACONGTY VARCHAR(4) NOT NULL,
    MALH VARCHAR(4) NOT NULL,
    DONVITINH NVARCHAR(4) NULL,
    SOLUONG INT NULL
)

ALTER TABLE LOAIHANG
ADD CONSTRAINT PK_LOAIHANG_MALH
PRIMARY KEY (MALH)

ALTER TABLE NHACUNGCAP
ADD CONSTRAINT PK_NHACUNGCAP_MACONGTY
PRIMARY KEY (MACONGTY)

ALTER TABLE MATHANG
ADD CONSTRAINT PK_MATHANG_MAHANG
PRIMARY KEY (MAHANG)

ALTER TABLE MATHANG
ADD CONSTRAINT FK_MATHANG_MACONGTY
FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY)

ALTER TABLE MATHANG
ADD CONSTRAINT FK_MATHANG_MALH
FOREIGN KEY (MALH) REFERENCES LOAIHANG(MALH)

ALTER TABLE LOAIHANG
ALTER COLUMN TENLH NVARCHAR(50) NULL

ALTER TABLE MATHANG
ADD CONSTRAINT UQ_MATHANG_TENHANG
UNIQUE (TENHANG)

ALTER TABLE MATHANG
ADD DONGIA FLOAT NULL